// Countries that have some anomalities in their names (such as special chars, brackets, or multiple variants) are collected here
const INITIAL_CODES = {
    Brunei: "BRN",
    "Mainland China": "CHN",
    US: "USA",
    Iran: "IRN",
    "South Korea": "KOR",
    "Korea, South": "KOR",
    Korea: "KOR",
    "Taiwan*": "TWN",
    UK: "GBR",
    "United Kingdom": "GBR",
    Czechia: "CZE",
    Russia: "RUS",
    "United Arab Emirates": "UAE",
    Macau: "MAC",
    "North Macedonia": "MKD",
    Venezuela: "VEN",
    Vietnam: "VNM",
    "Cote d'Ivoire": "CIV",
    "West Bank and Gaza": "PSE",
    Kosovo: "KOS",
    "Congo (Kinshasa)": "COD",
    "Congo (Brazzaville)": "COG",
    Tanzania: "TZA",
    Burma: "MMR",
    Syria: "SYR",
    Laos: "LAO",
    Eswatini: "SWZ",
};