// these used to be fetched from api provided by staff, which is now down.
// using this as a backup until I get around finding a similar api
const neighbours = [
  {
    name: "Afghanistan",
    alpha2Code: "AF",
    alpha3Code: "AFG",
    borders: ["IRN", "PAK", "TKM", "UZB", "TJK", "CHN"],
  },
  {
    name: "Åland Islands",
    alpha2Code: "AX",
    alpha3Code: "ALA",
    borders: [],
  },
  {
    name: "Albania",
    alpha2Code: "AL",
    alpha3Code: "ALB",
    borders: ["MNE", "GRC", "MKD", "KOS"],
  },
  {
    name: "Algeria",
    alpha2Code: "DZ",
    alpha3Code: "DZA",
    borders: ["TUN", "LBY", "NER", "ESH", "MRT", "MLI", "MAR"],
  },
  {
    name: "American Samoa",
    alpha2Code: "AS",
    alpha3Code: "ASM",
    borders: [],
  },
  {
    name: "Andorra",
    alpha2Code: "AD",
    alpha3Code: "AND",
    borders: ["FRA", "ESP"],
  },
  {
    name: "Angola",
    alpha2Code: "AO",
    alpha3Code: "AGO",
    borders: ["COG", "COD", "ZMB", "NAM"],
  },
  {
    name: "Anguilla",
    alpha2Code: "AI",
    alpha3Code: "AIA",
    borders: [],
  },
  {
    name: "Antarctica",
    alpha2Code: "AQ",
    alpha3Code: "ATA",
    borders: [],
  },
  {
    name: "Antigua and Barbuda",
    alpha2Code: "AG",
    alpha3Code: "ATG",
    borders: [],
  },
  {
    name: "Argentina",
    alpha2Code: "AR",
    alpha3Code: "ARG",
    borders: ["BOL", "BRA", "CHL", "PRY", "URY"],
  },
  {
    name: "Armenia",
    alpha2Code: "AM",
    alpha3Code: "ARM",
    borders: ["AZE", "GEO", "IRN", "TUR"],
  },
  { name: "Aruba", alpha2Code: "AW", alpha3Code: "ABW", borders: [] },
  {
    name: "Australia",
    alpha2Code: "AU",
    alpha3Code: "AUS",
    borders: [],
  },
  {
    name: "Austria",
    alpha2Code: "AT",
    alpha3Code: "AUT",
    borders: ["CZE", "DEU", "HUN", "ITA", "LIE", "SVK", "SVN", "CHE"],
  },
  {
    name: "Azerbaijan",
    alpha2Code: "AZ",
    alpha3Code: "AZE",
    borders: ["ARM", "GEO", "IRN", "RUS", "TUR"],
  },
  { name: "Bahamas", alpha2Code: "BS", alpha3Code: "BHS", borders: [] },
  { name: "Bahrain", alpha2Code: "BH", alpha3Code: "BHR", borders: [] },
  {
    name: "Bangladesh",
    alpha2Code: "BD",
    alpha3Code: "BGD",
    borders: ["MMR", "IND"],
  },
  {
    name: "Barbados",
    alpha2Code: "BB",
    alpha3Code: "BRB",
    borders: [],
  },
  {
    name: "Belarus",
    alpha2Code: "BY",
    alpha3Code: "BLR",
    borders: ["LVA", "LTU", "POL", "RUS", "UKR"],
  },
  {
    name: "Belgium",
    alpha2Code: "BE",
    alpha3Code: "BEL",
    borders: ["FRA", "DEU", "LUX", "NLD"],
  },
  {
    name: "Belize",
    alpha2Code: "BZ",
    alpha3Code: "BLZ",
    borders: ["GTM", "MEX"],
  },
  {
    name: "Benin",
    alpha2Code: "BJ",
    alpha3Code: "BEN",
    borders: ["BFA", "NER", "NGA", "TGO"],
  },
  { name: "Bermuda", alpha2Code: "BM", alpha3Code: "BMU", borders: [] },
  {
    name: "Bhutan",
    alpha2Code: "BT",
    alpha3Code: "BTN",
    borders: ["CHN", "IND"],
  },
  {
    name: "Bolivia (Plurinational State of)",
    alpha2Code: "BO",
    alpha3Code: "BOL",
    borders: ["ARG", "BRA", "CHL", "PRY", "PER"],
  },
  {
    name: "Bonaire, Sint Eustatius and Saba",
    alpha2Code: "BQ",
    alpha3Code: "BES",
    borders: [],
  },
  {
    name: "Bosnia and Herzegovina",
    alpha2Code: "BA",
    alpha3Code: "BIH",
    borders: ["HRV", "MNE", "SRB"],
  },
  {
    name: "Botswana",
    alpha2Code: "BW",
    alpha3Code: "BWA",
    borders: ["NAM", "ZAF", "ZMB", "ZWE"],
  },
  {
    name: "Bouvet Island",
    alpha2Code: "BV",
    alpha3Code: "BVT",
    borders: [],
  },
  {
    name: "Brazil",
    alpha2Code: "BR",
    alpha3Code: "BRA",
    borders: [
      "ARG",
      "BOL",
      "COL",
      "GUF",
      "GUY",
      "PRY",
      "PER",
      "SUR",
      "URY",
      "VEN",
    ],
  },
  {
    name: "British Indian Ocean Territory",
    alpha2Code: "IO",
    alpha3Code: "IOT",
    borders: [],
  },
  {
    name: "United States Minor Outlying Islands",
    alpha2Code: "UM",
    alpha3Code: "UMI",
    borders: [],
  },
  {
    name: "Virgin Islands (British)",
    alpha2Code: "VG",
    alpha3Code: "VGB",
    borders: [],
  },
  {
    name: "Virgin Islands (U.S.)",
    alpha2Code: "VI",
    alpha3Code: "VIR",
    borders: [],
  },
  {
    name: "Brunei Darussalam",
    alpha2Code: "BN",
    alpha3Code: "BRN",
    borders: ["MYS"],
  },
  {
    name: "Bulgaria",
    alpha2Code: "BG",
    alpha3Code: "BGR",
    borders: ["GRC", "MKD", "ROU", "SRB", "TUR"],
  },
  {
    name: "Burkina Faso",
    alpha2Code: "BF",
    alpha3Code: "BFA",
    borders: ["BEN", "CIV", "GHA", "MLI", "NER", "TGO"],
  },
  {
    name: "Burundi",
    alpha2Code: "BI",
    alpha3Code: "BDI",
    borders: ["COD", "RWA", "TZA"],
  },
  {
    name: "Cambodia",
    alpha2Code: "KH",
    alpha3Code: "KHM",
    borders: ["LAO", "THA", "VNM"],
  },
  {
    name: "Cameroon",
    alpha2Code: "CM",
    alpha3Code: "CMR",
    borders: ["CAF", "TCD", "COG", "GNQ", "GAB", "NGA"],
  },
  {
    name: "Canada",
    alpha2Code: "CA",
    alpha3Code: "CAN",
    borders: ["USA"],
  },
  {
    name: "Cabo Verde",
    alpha2Code: "CV",
    alpha3Code: "CPV",
    borders: [],
  },
  {
    name: "Cayman Islands",
    alpha2Code: "KY",
    alpha3Code: "CYM",
    borders: [],
  },
  {
    name: "Central African Republic",
    alpha2Code: "CF",
    alpha3Code: "CAF",
    borders: ["CMR", "TCD", "COD", "COG", "SSD", "SDN"],
  },
  {
    name: "Chad",
    alpha2Code: "TD",
    alpha3Code: "TCD",
    borders: ["CMR", "CAF", "LBY", "NER", "NGA", "SSD"],
  },
  {
    name: "Chile",
    alpha2Code: "CL",
    alpha3Code: "CHL",
    borders: ["ARG", "BOL", "PER"],
  },
  {
    name: "China",
    alpha2Code: "CN",
    alpha3Code: "CHN",
    borders: [
      "AFG",
      "BTN",
      "MMR",
      "HKG",
      "IND",
      "KAZ",
      "PRK",
      "KGZ",
      "LAO",
      "MAC",
      "MNG",
      "PAK",
      "RUS",
      "TJK",
      "VNM",
    ],
  },
  {
    name: "Christmas Island",
    alpha2Code: "CX",
    alpha3Code: "CXR",
    borders: [],
  },
  {
    name: "Cocos (Keeling) Islands",
    alpha2Code: "CC",
    alpha3Code: "CCK",
    borders: [],
  },
  {
    name: "Colombia",
    alpha2Code: "CO",
    alpha3Code: "COL",
    borders: ["BRA", "ECU", "PAN", "PER", "VEN"],
  },
  { name: "Comoros", alpha2Code: "KM", alpha3Code: "COM", borders: [] },
  {
    name: "Congo",
    alpha2Code: "CG",
    alpha3Code: "COG",
    borders: ["AGO", "CMR", "CAF", "COD", "GAB"],
  },
  {
    name: "Congo (Democratic Republic of the)",
    alpha2Code: "CD",
    alpha3Code: "COD",
    borders: ["AGO", "BDI", "CAF", "COG", "RWA", "SSD", "TZA", "UGA", "ZMB"],
  },
  {
    name: "Cook Islands",
    alpha2Code: "CK",
    alpha3Code: "COK",
    borders: [],
  },
  {
    name: "Costa Rica",
    alpha2Code: "CR",
    alpha3Code: "CRI",
    borders: ["NIC", "PAN"],
  },
  {
    name: "Croatia",
    alpha2Code: "HR",
    alpha3Code: "HRV",
    borders: ["BIH", "HUN", "MNE", "SRB", "SVN"],
  },
  { name: "Cuba", alpha2Code: "CU", alpha3Code: "CUB", borders: [] },
  { name: "Curaçao", alpha2Code: "CW", alpha3Code: "CUW", borders: [] },
  {
    name: "Cyprus",
    alpha2Code: "CY",
    alpha3Code: "CYP",
    borders: ["GBR"],
  },
  {
    name: "Czech Republic",
    alpha2Code: "CZ",
    alpha3Code: "CZE",
    borders: ["AUT", "DEU", "POL", "SVK"],
  },
  {
    name: "Denmark",
    alpha2Code: "DK",
    alpha3Code: "DNK",
    borders: ["DEU"],
  },
  {
    name: "Djibouti",
    alpha2Code: "DJ",
    alpha3Code: "DJI",
    borders: ["ERI", "ETH", "SOM"],
  },
  {
    name: "Dominica",
    alpha2Code: "DM",
    alpha3Code: "DMA",
    borders: [],
  },
  {
    name: "Dominican Republic",
    alpha2Code: "DO",
    alpha3Code: "DOM",
    borders: ["HTI"],
  },
  {
    name: "Ecuador",
    alpha2Code: "EC",
    alpha3Code: "ECU",
    borders: ["COL", "PER"],
  },
  {
    name: "Egypt",
    alpha2Code: "EG",
    alpha3Code: "EGY",
    borders: ["ISR", "LBY", "SDN"],
  },
  {
    name: "El Salvador",
    alpha2Code: "SV",
    alpha3Code: "SLV",
    borders: ["GTM", "HND"],
  },
  {
    name: "Equatorial Guinea",
    alpha2Code: "GQ",
    alpha3Code: "GNQ",
    borders: ["CMR", "GAB"],
  },
  {
    name: "Eritrea",
    alpha2Code: "ER",
    alpha3Code: "ERI",
    borders: ["DJI", "ETH", "SDN"],
  },
  {
    name: "Estonia",
    alpha2Code: "EE",
    alpha3Code: "EST",
    borders: ["LVA", "RUS"],
  },
  {
    name: "Ethiopia",
    alpha2Code: "ET",
    alpha3Code: "ETH",
    borders: ["DJI", "ERI", "KEN", "SOM", "SSD", "SDN"],
  },
  {
    name: "Falkland Islands (Malvinas)",
    alpha2Code: "FK",
    alpha3Code: "FLK",
    borders: [],
  },
  {
    name: "Faroe Islands",
    alpha2Code: "FO",
    alpha3Code: "FRO",
    borders: [],
  },
  { name: "Fiji", alpha2Code: "FJ", alpha3Code: "FJI", borders: [] },
  {
    name: "Finland",
    alpha2Code: "FI",
    alpha3Code: "FIN",
    borders: ["NOR", "SWE", "RUS"],
  },
  {
    name: "France",
    alpha2Code: "FR",
    alpha3Code: "FRA",
    borders: ["AND", "BEL", "DEU", "ITA", "LUX", "MCO", "ESP", "CHE"],
  },
  {
    name: "French Guiana",
    alpha2Code: "GF",
    alpha3Code: "GUF",
    borders: ["BRA", "SUR"],
  },
  {
    name: "French Polynesia",
    alpha2Code: "PF",
    alpha3Code: "PYF",
    borders: [],
  },
  {
    name: "French Southern Territories",
    alpha2Code: "TF",
    alpha3Code: "ATF",
    borders: [],
  },
  {
    name: "Gabon",
    alpha2Code: "GA",
    alpha3Code: "GAB",
    borders: ["CMR", "COG", "GNQ"],
  },
  {
    name: "Gambia",
    alpha2Code: "GM",
    alpha3Code: "GMB",
    borders: ["SEN"],
  },
  {
    name: "Georgia",
    alpha2Code: "GE",
    alpha3Code: "GEO",
    borders: ["ARM", "AZE", "RUS", "TUR"],
  },
  {
    name: "Germany",
    alpha2Code: "DE",
    alpha3Code: "DEU",
    borders: ["AUT", "BEL", "CZE", "DNK", "FRA", "LUX", "NLD", "POL", "CHE"],
  },
  {
    name: "Ghana",
    alpha2Code: "GH",
    alpha3Code: "GHA",
    borders: ["BFA", "CIV", "TGO"],
  },
  {
    name: "Gibraltar",
    alpha2Code: "GI",
    alpha3Code: "GIB",
    borders: ["ESP"],
  },
  {
    name: "Greece",
    alpha2Code: "GR",
    alpha3Code: "GRC",
    borders: ["ALB", "BGR", "TUR", "MKD"],
  },
  {
    name: "Greenland",
    alpha2Code: "GL",
    alpha3Code: "GRL",
    borders: [],
  },
  { name: "Grenada", alpha2Code: "GD", alpha3Code: "GRD", borders: [] },
  {
    name: "Guadeloupe",
    alpha2Code: "GP",
    alpha3Code: "GLP",
    borders: [],
  },
  { name: "Guam", alpha2Code: "GU", alpha3Code: "GUM", borders: [] },
  {
    name: "Guatemala",
    alpha2Code: "GT",
    alpha3Code: "GTM",
    borders: ["BLZ", "SLV", "HND", "MEX"],
  },
  {
    name: "Guernsey",
    alpha2Code: "GG",
    alpha3Code: "GGY",
    borders: [],
  },
  {
    name: "Guinea",
    alpha2Code: "GN",
    alpha3Code: "GIN",
    borders: ["CIV", "GNB", "LBR", "MLI", "SEN", "SLE"],
  },
  {
    name: "Guinea-Bissau",
    alpha2Code: "GW",
    alpha3Code: "GNB",
    borders: ["GIN", "SEN"],
  },
  {
    name: "Guyana",
    alpha2Code: "GY",
    alpha3Code: "GUY",
    borders: ["BRA", "SUR", "VEN"],
  },
  {
    name: "Haiti",
    alpha2Code: "HT",
    alpha3Code: "HTI",
    borders: ["DOM"],
  },
  {
    name: "Heard Island and McDonald Islands",
    alpha2Code: "HM",
    alpha3Code: "HMD",
    borders: [],
  },
  {
    name: "Holy See",
    alpha2Code: "VA",
    alpha3Code: "VAT",
    borders: ["ITA"],
  },
  {
    name: "Honduras",
    alpha2Code: "HN",
    alpha3Code: "HND",
    borders: ["GTM", "SLV", "NIC"],
  },
  {
    name: "Hong Kong",
    alpha2Code: "HK",
    alpha3Code: "HKG",
    borders: ["CHN"],
  },
  {
    name: "Hungary",
    alpha2Code: "HU",
    alpha3Code: "HUN",
    borders: ["AUT", "HRV", "ROU", "SRB", "SVK", "SVN", "UKR"],
  },
  { name: "Iceland", alpha2Code: "IS", alpha3Code: "ISL", borders: [] },
  {
    name: "India",
    alpha2Code: "IN",
    alpha3Code: "IND",
    borders: ["AFG", "BGD", "BTN", "MMR", "CHN", "NPL", "PAK", "LKA"],
  },
  {
    name: "Indonesia",
    alpha2Code: "ID",
    alpha3Code: "IDN",
    borders: ["TLS", "MYS", "PNG"],
  },
  {
    name: "Côte d'Ivoire",
    alpha2Code: "CI",
    alpha3Code: "CIV",
    borders: ["BFA", "GHA", "GIN", "LBR", "MLI"],
  },
  {
    name: "Iran (Islamic Republic of)",
    alpha2Code: "IR",
    alpha3Code: "IRN",
    borders: ["AFG", "ARM", "AZE", "IRQ", "PAK", "TUR", "TKM"],
  },
  {
    name: "Iraq",
    alpha2Code: "IQ",
    alpha3Code: "IRQ",
    borders: ["IRN", "JOR", "KWT", "SAU", "SYR", "TUR"],
  },
  {
    name: "Ireland",
    alpha2Code: "IE",
    alpha3Code: "IRL",
    borders: ["GBR"],
  },
  {
    name: "Isle of Man",
    alpha2Code: "IM",
    alpha3Code: "IMN",
    borders: [],
  },
  {
    name: "Israel",
    alpha2Code: "IL",
    alpha3Code: "ISR",
    borders: ["EGY", "JOR", "LBN", "SYR"],
  },
  {
    name: "Italy",
    alpha2Code: "IT",
    alpha3Code: "ITA",
    borders: ["AUT", "FRA", "SMR", "SVN", "CHE", "VAT"],
  },
  { name: "Jamaica", alpha2Code: "JM", alpha3Code: "JAM", borders: [] },
  { name: "Japan", alpha2Code: "JP", alpha3Code: "JPN", borders: [] },
  { name: "Jersey", alpha2Code: "JE", alpha3Code: "JEY", borders: [] },
  {
    name: "Jordan",
    alpha2Code: "JO",
    alpha3Code: "JOR",
    borders: ["IRQ", "ISR", "SAU", "SYR"],
  },
  {
    name: "Kazakhstan",
    alpha2Code: "KZ",
    alpha3Code: "KAZ",
    borders: ["CHN", "KGZ", "RUS", "TKM", "UZB"],
  },
  {
    name: "Kenya",
    alpha2Code: "KE",
    alpha3Code: "KEN",
    borders: ["ETH", "SOM", "SSD", "TZA", "UGA"],
  },
  {
    name: "Kiribati",
    alpha2Code: "KI",
    alpha3Code: "KIR",
    borders: [],
  },
  {
    name: "Kuwait",
    alpha2Code: "KW",
    alpha3Code: "KWT",
    borders: ["IRN", "SAU"],
  },
  {
    name: "Kyrgyzstan",
    alpha2Code: "KG",
    alpha3Code: "KGZ",
    borders: ["CHN", "KAZ", "TJK", "UZB"],
  },
  {
    name: "Lao People's Democratic Republic",
    alpha2Code: "LA",
    alpha3Code: "LAO",
    borders: ["MMR", "KHM", "CHN", "THA", "VNM"],
  },
  {
    name: "Latvia",
    alpha2Code: "LV",
    alpha3Code: "LVA",
    borders: ["BLR", "EST", "LTU", "RUS"],
  },
  {
    name: "Lebanon",
    alpha2Code: "LB",
    alpha3Code: "LBN",
    borders: ["ISR", "SYR"],
  },
  {
    name: "Lesotho",
    alpha2Code: "LS",
    alpha3Code: "LSO",
    borders: ["ZAF"],
  },
  {
    name: "Liberia",
    alpha2Code: "LR",
    alpha3Code: "LBR",
    borders: ["GIN", "CIV", "SLE"],
  },
  {
    name: "Libya",
    alpha2Code: "LY",
    alpha3Code: "LBY",
    borders: ["DZA", "TCD", "EGY", "NER", "SDN", "TUN"],
  },
  {
    name: "Liechtenstein",
    alpha2Code: "LI",
    alpha3Code: "LIE",
    borders: ["AUT", "CHE"],
  },
  {
    name: "Lithuania",
    alpha2Code: "LT",
    alpha3Code: "LTU",
    borders: ["BLR", "LVA", "POL", "RUS"],
  },
  {
    name: "Luxembourg",
    alpha2Code: "LU",
    alpha3Code: "LUX",
    borders: ["BEL", "FRA", "DEU"],
  },
  {
    name: "Macao",
    alpha2Code: "MO",
    alpha3Code: "MAC",
    borders: ["CHN"],
  },
  {
    name: "Macedonia (the former Yugoslav Republic of)",
    alpha2Code: "MK",
    alpha3Code: "MKD",
    borders: ["ALB", "BGR", "GRC", "KOS", "SRB"],
  },
  {
    name: "Madagascar",
    alpha2Code: "MG",
    alpha3Code: "MDG",
    borders: [],
  },
  {
    name: "Malawi",
    alpha2Code: "MW",
    alpha3Code: "MWI",
    borders: ["MOZ", "TZA", "ZMB"],
  },
  {
    name: "Malaysia",
    alpha2Code: "MY",
    alpha3Code: "MYS",
    borders: ["BRN", "IDN", "THA"],
  },
  {
    name: "Maldives",
    alpha2Code: "MV",
    alpha3Code: "MDV",
    borders: [],
  },
  {
    name: "Mali",
    alpha2Code: "ML",
    alpha3Code: "MLI",
    borders: ["DZA", "BFA", "GIN", "CIV", "MRT", "NER", "SEN"],
  },
  { name: "Malta", alpha2Code: "MT", alpha3Code: "MLT", borders: [] },
  {
    name: "Marshall Islands",
    alpha2Code: "MH",
    alpha3Code: "MHL",
    borders: [],
  },
  {
    name: "Martinique",
    alpha2Code: "MQ",
    alpha3Code: "MTQ",
    borders: [],
  },
  {
    name: "Mauritania",
    alpha2Code: "MR",
    alpha3Code: "MRT",
    borders: ["DZA", "MLI", "SEN", "ESH"],
  },
  {
    name: "Mauritius",
    alpha2Code: "MU",
    alpha3Code: "MUS",
    borders: [],
  },
  { name: "Mayotte", alpha2Code: "YT", alpha3Code: "MYT", borders: [] },
  {
    name: "Mexico",
    alpha2Code: "MX",
    alpha3Code: "MEX",
    borders: ["BLZ", "GTM", "USA"],
  },
  {
    name: "Micronesia (Federated States of)",
    alpha2Code: "FM",
    alpha3Code: "FSM",
    borders: [],
  },
  {
    name: "Moldova (Republic of)",
    alpha2Code: "MD",
    alpha3Code: "MDA",
    borders: ["ROU", "UKR"],
  },
  {
    name: "Monaco",
    alpha2Code: "MC",
    alpha3Code: "MCO",
    borders: ["FRA"],
  },
  {
    name: "Mongolia",
    alpha2Code: "MN",
    alpha3Code: "MNG",
    borders: ["CHN", "RUS"],
  },
  {
    name: "Montenegro",
    alpha2Code: "ME",
    alpha3Code: "MNE",
    borders: ["ALB", "BIH", "HRV", "KOS", "SRB"],
  },
  {
    name: "Montserrat",
    alpha2Code: "MS",
    alpha3Code: "MSR",
    borders: [],
  },
  {
    name: "Morocco",
    alpha2Code: "MA",
    alpha3Code: "MAR",
    borders: ["DZA", "ESH", "ESP"],
  },
  {
    name: "Mozambique",
    alpha2Code: "MZ",
    alpha3Code: "MOZ",
    borders: ["MWI", "ZAF", "SWZ", "TZA", "ZMB", "ZWE"],
  },
  {
    name: "Myanmar",
    alpha2Code: "MM",
    alpha3Code: "MMR",
    borders: ["BGD", "CHN", "IND", "LAO", "THA"],
  },
  {
    name: "Namibia",
    alpha2Code: "NA",
    alpha3Code: "NAM",
    borders: ["AGO", "BWA", "ZAF", "ZMB"],
  },
  { name: "Nauru", alpha2Code: "NR", alpha3Code: "NRU", borders: [] },
  {
    name: "Nepal",
    alpha2Code: "NP",
    alpha3Code: "NPL",
    borders: ["CHN", "IND"],
  },
  {
    name: "Netherlands",
    alpha2Code: "NL",
    alpha3Code: "NLD",
    borders: ["BEL", "DEU"],
  },
  {
    name: "New Caledonia",
    alpha2Code: "NC",
    alpha3Code: "NCL",
    borders: [],
  },
  {
    name: "New Zealand",
    alpha2Code: "NZ",
    alpha3Code: "NZL",
    borders: [],
  },
  {
    name: "Nicaragua",
    alpha2Code: "NI",
    alpha3Code: "NIC",
    borders: ["CRI", "HND"],
  },
  {
    name: "Niger",
    alpha2Code: "NE",
    alpha3Code: "NER",
    borders: ["DZA", "BEN", "BFA", "TCD", "LBY", "MLI", "NGA"],
  },
  {
    name: "Nigeria",
    alpha2Code: "NG",
    alpha3Code: "NGA",
    borders: ["BEN", "CMR", "TCD", "NER"],
  },
  { name: "Niue", alpha2Code: "NU", alpha3Code: "NIU", borders: [] },
  {
    name: "Norfolk Island",
    alpha2Code: "NF",
    alpha3Code: "NFK",
    borders: [],
  },
  {
    name: "Korea (Democratic People's Republic of)",
    alpha2Code: "KP",
    alpha3Code: "PRK",
    borders: ["CHN", "KOR", "RUS"],
  },
  {
    name: "Northern Mariana Islands",
    alpha2Code: "MP",
    alpha3Code: "MNP",
    borders: [],
  },
  {
    name: "Norway",
    alpha2Code: "NO",
    alpha3Code: "NOR",
    borders: ["FIN", "SWE", "RUS"],
  },
  {
    name: "Oman",
    alpha2Code: "OM",
    alpha3Code: "OMN",
    borders: ["SAU", "ARE", "YEM"],
  },
  {
    name: "Pakistan",
    alpha2Code: "PK",
    alpha3Code: "PAK",
    borders: ["AFG", "CHN", "IND", "IRN"],
  },
  { name: "Palau", alpha2Code: "PW", alpha3Code: "PLW", borders: [] },
  {
    name: "Palestine, State of",
    alpha2Code: "PS",
    alpha3Code: "PSE",
    borders: ["ISR", "EGY", "JOR"],
  },
  {
    name: "Panama",
    alpha2Code: "PA",
    alpha3Code: "PAN",
    borders: ["COL", "CRI"],
  },
  {
    name: "Papua New Guinea",
    alpha2Code: "PG",
    alpha3Code: "PNG",
    borders: ["IDN"],
  },
  {
    name: "Paraguay",
    alpha2Code: "PY",
    alpha3Code: "PRY",
    borders: ["ARG", "BOL", "BRA"],
  },
  {
    name: "Peru",
    alpha2Code: "PE",
    alpha3Code: "PER",
    borders: ["BOL", "BRA", "CHL", "COL", "ECU"],
  },
  {
    name: "Philippines",
    alpha2Code: "PH",
    alpha3Code: "PHL",
    borders: [],
  },
  {
    name: "Pitcairn",
    alpha2Code: "PN",
    alpha3Code: "PCN",
    borders: [],
  },
  {
    name: "Poland",
    alpha2Code: "PL",
    alpha3Code: "POL",
    borders: ["BLR", "CZE", "DEU", "LTU", "RUS", "SVK", "UKR"],
  },
  {
    name: "Portugal",
    alpha2Code: "PT",
    alpha3Code: "PRT",
    borders: ["ESP"],
  },
  {
    name: "Puerto Rico",
    alpha2Code: "PR",
    alpha3Code: "PRI",
    borders: [],
  },
  {
    name: "Qatar",
    alpha2Code: "QA",
    alpha3Code: "QAT",
    borders: ["SAU"],
  },
  {
    name: "Republic of Kosovo",
    alpha2Code: "XK",
    alpha3Code: "KOS",
    borders: ["ALB", "MKD", "MNE", "SRB"],
  },
  { name: "Réunion", alpha2Code: "RE", alpha3Code: "REU", borders: [] },
  {
    name: "Romania",
    alpha2Code: "RO",
    alpha3Code: "ROU",
    borders: ["BGR", "HUN", "MDA", "SRB", "UKR"],
  },
  {
    name: "Russian Federation",
    alpha2Code: "RU",
    alpha3Code: "RUS",
    borders: [
      "AZE",
      "BLR",
      "CHN",
      "EST",
      "FIN",
      "GEO",
      "KAZ",
      "PRK",
      "LVA",
      "LTU",
      "MNG",
      "NOR",
      "POL",
      "UKR",
    ],
  },
  {
    name: "Rwanda",
    alpha2Code: "RW",
    alpha3Code: "RWA",
    borders: ["BDI", "COD", "TZA", "UGA"],
  },
  {
    name: "Saint Barthélemy",
    alpha2Code: "BL",
    alpha3Code: "BLM",
    borders: [],
  },
  {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    alpha2Code: "SH",
    alpha3Code: "SHN",
    borders: [],
  },
  {
    name: "Saint Kitts and Nevis",
    alpha2Code: "KN",
    alpha3Code: "KNA",
    borders: [],
  },
  {
    name: "Saint Lucia",
    alpha2Code: "LC",
    alpha3Code: "LCA",
    borders: [],
  },
  {
    name: "Saint Martin (French part)",
    alpha2Code: "MF",
    alpha3Code: "MAF",
    borders: ["SXM", "NLD"],
  },
  {
    name: "Saint Pierre and Miquelon",
    alpha2Code: "PM",
    alpha3Code: "SPM",
    borders: [],
  },
  {
    name: "Saint Vincent and the Grenadines",
    alpha2Code: "VC",
    alpha3Code: "VCT",
    borders: [],
  },
  { name: "Samoa", alpha2Code: "WS", alpha3Code: "WSM", borders: [] },
  {
    name: "San Marino",
    alpha2Code: "SM",
    alpha3Code: "SMR",
    borders: ["ITA"],
  },
  {
    name: "Sao Tome and Principe",
    alpha2Code: "ST",
    alpha3Code: "STP",
    borders: [],
  },
  {
    name: "Saudi Arabia",
    alpha2Code: "SA",
    alpha3Code: "SAU",
    borders: ["IRQ", "JOR", "KWT", "OMN", "QAT", "ARE", "YEM"],
  },
  {
    name: "Senegal",
    alpha2Code: "SN",
    alpha3Code: "SEN",
    borders: ["GMB", "GIN", "GNB", "MLI", "MRT"],
  },
  {
    name: "Serbia",
    alpha2Code: "RS",
    alpha3Code: "SRB",
    borders: ["BIH", "BGR", "HRV", "HUN", "KOS", "MKD", "MNE", "ROU"],
  },
  {
    name: "Seychelles",
    alpha2Code: "SC",
    alpha3Code: "SYC",
    borders: [],
  },
  {
    name: "Sierra Leone",
    alpha2Code: "SL",
    alpha3Code: "SLE",
    borders: ["GIN", "LBR"],
  },
  {
    name: "Singapore",
    alpha2Code: "SG",
    alpha3Code: "SGP",
    borders: [],
  },
  {
    name: "Sint Maarten (Dutch part)",
    alpha2Code: "SX",
    alpha3Code: "SXM",
    borders: ["MAF"],
  },
  {
    name: "Slovakia",
    alpha2Code: "SK",
    alpha3Code: "SVK",
    borders: ["AUT", "CZE", "HUN", "POL", "UKR"],
  },
  {
    name: "Slovenia",
    alpha2Code: "SI",
    alpha3Code: "SVN",
    borders: ["AUT", "HRV", "ITA", "HUN"],
  },
  {
    name: "Solomon Islands",
    alpha2Code: "SB",
    alpha3Code: "SLB",
    borders: [],
  },
  {
    name: "Somalia",
    alpha2Code: "SO",
    alpha3Code: "SOM",
    borders: ["DJI", "ETH", "KEN"],
  },
  {
    name: "South Africa",
    alpha2Code: "ZA",
    alpha3Code: "ZAF",
    borders: ["BWA", "LSO", "MOZ", "NAM", "SWZ", "ZWE"],
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    alpha2Code: "GS",
    alpha3Code: "SGS",
    borders: [],
  },
  {
    name: "Korea (Republic of)",
    alpha2Code: "KR",
    alpha3Code: "KOR",
    borders: ["PRK"],
  },
  {
    name: "South Sudan",
    alpha2Code: "SS",
    alpha3Code: "SSD",
    borders: ["CAF", "COD", "ETH", "KEN", "SDN", "UGA"],
  },
  {
    name: "Spain",
    alpha2Code: "ES",
    alpha3Code: "ESP",
    borders: ["AND", "FRA", "GIB", "PRT", "MAR"],
  },
  {
    name: "Sri Lanka",
    alpha2Code: "LK",
    alpha3Code: "LKA",
    borders: ["IND"],
  },
  {
    name: "Sudan",
    alpha2Code: "SD",
    alpha3Code: "SDN",
    borders: ["CAF", "TCD", "EGY", "ERI", "ETH", "LBY", "SSD"],
  },
  {
    name: "Suriname",
    alpha2Code: "SR",
    alpha3Code: "SUR",
    borders: ["BRA", "GUF", "FRA", "GUY"],
  },
  {
    name: "Svalbard and Jan Mayen",
    alpha2Code: "SJ",
    alpha3Code: "SJM",
    borders: [],
  },
  {
    name: "Swaziland",
    alpha2Code: "SZ",
    alpha3Code: "SWZ",
    borders: ["MOZ", "ZAF"],
  },
  {
    name: "Sweden",
    alpha2Code: "SE",
    alpha3Code: "SWE",
    borders: ["FIN", "NOR"],
  },
  {
    name: "Switzerland",
    alpha2Code: "CH",
    alpha3Code: "CHE",
    borders: ["AUT", "FRA", "ITA", "LIE", "DEU"],
  },
  {
    name: "Syrian Arab Republic",
    alpha2Code: "SY",
    alpha3Code: "SYR",
    borders: ["IRQ", "ISR", "JOR", "LBN", "TUR"],
  },
  { name: "Taiwan", alpha2Code: "TW", alpha3Code: "TWN", borders: [] },
  {
    name: "Tajikistan",
    alpha2Code: "TJ",
    alpha3Code: "TJK",
    borders: ["AFG", "CHN", "KGZ", "UZB"],
  },
  {
    name: "Tanzania, United Republic of",
    alpha2Code: "TZ",
    alpha3Code: "TZA",
    borders: ["BDI", "COD", "KEN", "MWI", "MOZ", "RWA", "UGA", "ZMB"],
  },
  {
    name: "Thailand",
    alpha2Code: "TH",
    alpha3Code: "THA",
    borders: ["MMR", "KHM", "LAO", "MYS"],
  },
  {
    name: "Timor-Leste",
    alpha2Code: "TL",
    alpha3Code: "TLS",
    borders: ["IDN"],
  },
  {
    name: "Togo",
    alpha2Code: "TG",
    alpha3Code: "TGO",
    borders: ["BEN", "BFA", "GHA"],
  },
  { name: "Tokelau", alpha2Code: "TK", alpha3Code: "TKL", borders: [] },
  { name: "Tonga", alpha2Code: "TO", alpha3Code: "TON", borders: [] },
  {
    name: "Trinidad and Tobago",
    alpha2Code: "TT",
    alpha3Code: "TTO",
    borders: [],
  },
  {
    name: "Tunisia",
    alpha2Code: "TN",
    alpha3Code: "TUN",
    borders: ["DZA", "LBY"],
  },
  {
    name: "Turkey",
    alpha2Code: "TR",
    alpha3Code: "TUR",
    borders: ["ARM", "AZE", "BGR", "GEO", "GRC", "IRN", "IRQ", "SYR"],
  },
  {
    name: "Turkmenistan",
    alpha2Code: "TM",
    alpha3Code: "TKM",
    borders: ["AFG", "IRN", "KAZ", "UZB"],
  },
  {
    name: "Turks and Caicos Islands",
    alpha2Code: "TC",
    alpha3Code: "TCA",
    borders: [],
  },
  { name: "Tuvalu", alpha2Code: "TV", alpha3Code: "TUV", borders: [] },
  {
    name: "Uganda",
    alpha2Code: "UG",
    alpha3Code: "UGA",
    borders: ["COD", "KEN", "RWA", "SSD", "TZA"],
  },
  {
    name: "Ukraine",
    alpha2Code: "UA",
    alpha3Code: "UKR",
    borders: ["BLR", "HUN", "MDA", "POL", "ROU", "RUS", "SVK"],
  },
  {
    name: "United Arab Emirates",
    alpha2Code: "AE",
    alpha3Code: "ARE",
    borders: ["OMN", "SAU"],
  },
  {
    name: "United Kingdom of Great Britain and Northern Ireland",
    alpha2Code: "GB",
    alpha3Code: "GBR",
    borders: ["IRL"],
  },
  {
    name: "United States of America",
    alpha2Code: "US",
    alpha3Code: "USA",
    borders: ["CAN", "MEX"],
  },
  {
    name: "Uruguay",
    alpha2Code: "UY",
    alpha3Code: "URY",
    borders: ["ARG", "BRA"],
  },
  {
    name: "Uzbekistan",
    alpha2Code: "UZ",
    alpha3Code: "UZB",
    borders: ["AFG", "KAZ", "KGZ", "TJK", "TKM"],
  },
  { name: "Vanuatu", alpha2Code: "VU", alpha3Code: "VUT", borders: [] },
  {
    name: "Venezuela (Bolivarian Republic of)",
    alpha2Code: "VE",
    alpha3Code: "VEN",
    borders: ["BRA", "COL", "GUY"],
  },
  {
    name: "Viet Nam",
    alpha2Code: "VN",
    alpha3Code: "VNM",
    borders: ["KHM", "CHN", "LAO"],
  },
  {
    name: "Wallis and Futuna",
    alpha2Code: "WF",
    alpha3Code: "WLF",
    borders: [],
  },
  {
    name: "Western Sahara",
    alpha2Code: "EH",
    alpha3Code: "ESH",
    borders: ["DZA", "MRT", "MAR"],
  },
  {
    name: "Yemen",
    alpha2Code: "YE",
    alpha3Code: "YEM",
    borders: ["OMN", "SAU"],
  },
  {
    name: "Zambia",
    alpha2Code: "ZM",
    alpha3Code: "ZMB",
    borders: ["AGO", "BWA", "COD", "MWI", "MOZ", "NAM", "TZA", "ZWE"],
  },
  {
    name: "Zimbabwe",
    alpha2Code: "ZW",
    alpha3Code: "ZWE",
    borders: ["BWA", "MOZ", "ZAF", "ZMB"],
  },
];